# Change these first
owner: agility-game # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Agility Game Landing Page
    url: https://agility-game.com
  - name: Agility Game API
    url: https://app.agility-game.com/live
    icon: https://agility-game.com/logo.png
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.agility-game.com
  # baseUrl: /uptime
  logoUrl: https://agility-game.com/logo-square.svg
  name: Agility Game Uptime
  introTitle: "Agility Game server status."
  introMessage: Agility Game web and email service status
  navbar:
     - title: GitHub
       href: https://github.com/agility-game
     - title: Email Delay
       href: https://chart-embed.service.eu.newrelic.com/herald/4543cfed-08a2-423c-abae-6f1d34de3673?height=600px&timepicker=true

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
